name: Vercel Deployment
on:
  push:
    branches: [main]  # Changed from vercel to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Vercel CLI
        run: npm install -g vercel
        
      - name: Setup Environment Variables
        run: |
          vercel env add TWITCH_CLIENT_ID --yes
          vercel env add TWITCH_CLIENT_SECRET --yes
          vercel env add TWITCH_CHANNEL --yes
          vercel env add TWITCH_REDIRECT_URI --yes
          vercel env add TWITCH_SCOPES --yes --value "chat:read chat:edit"
          vercel env add TWITCH_BOT_USERNAME --yes
          vercel env add TWITCH_OAUTH_TOKEN --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          
      - name: Deploy to Vercel
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
